# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain python dependencies
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    groups:
      uv-dependencies:
        patterns:
          - "*"

  # Maintain dependencies for GitHub Actions (/.github/workflows)
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/workflows/*"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    labels:
      - dependencies
    groups:
      github-actions:
        patterns:
          - "*"
