---

default_install_hook_types: [ pre-commit, commit-msg ]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      # Run the linter.
      - id: ruff-check
        args:
          - --select=I
          - --fix
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
        name: check-json-schema
      - id: mixed-line-ending
        name: enforce-lf-newline
        args:
          - --fix=lf
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
