---
name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

env:
  # Ref: https://docs.astral.sh/uv/concepts/projects/sync/#checking-if-the-lockfile-is-up-to-date
  UV_FROZEN: "true"

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install environment
        uses: ./.github/workflows/env-install

      - name: Lint
        run: uv run poe lint

  build:
    needs:
      - lint
    strategy:
      matrix:
        os:
          - macos-14
          - macos-13
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install environment
        uses: ./.github/workflows/env-install

      - name: Build
        run: uv run poe build

  test:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install environment
        uses: ./.github/workflows/env-install

      - name: Install terraform binary
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Test
        run: uv run poe test

  test-install:
    runs-on: ubuntu-latest
    # If you change the branch name in  scripts/release.py please
    # update the condition below.
    # We cannot test the install if the release has not happened yet.
    if: ${{ !startsWith(github.head_ref, 'feat/pre-release-v') }}
    steps:
      - uses: actions/checkout@v4

      - name: run install.sh
        run: ./install.sh

      - name: run terranova
        run: |-
          terranova --version
