---

name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/workflows/env-setup

      - name: Lint
        run: poetry run poe lint

  build:
    needs:
      - lint
    strategy:
      matrix:
        os:
          - macos-14
          - macos-13
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/workflows/env-setup
        with:
          shell: ${{ matrix.os == 'windows-latest' && 'cmd' || 'bash' }}

      - name: Build
        run: poetry run poe build

      - uses: actions/upload-artifact@v4
        with:
          name: terranova-${{ matrix.os }}
          path: 'dist/*'
          retention-days: 5

  test:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/workflows/env-setup

      - name: Install terraform binary
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Test
        run: poetry run poe test
